# Generated by Django 4.1.4 on 2022-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_object_id_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.PositiveSmallIntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')]),
        ),
    ]
